config/routes.rb
Rails.application.routes.draw do

  authenticated :user, ->(user) { user.admin?} do
    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
    end
  end
  
  authenticated :user do
    get 'notifications/:id', to: 'notifications#mark_and_redirect', as: 'mark_and_redirect_notification'
    get 'userpage', to: "userpage#show"
    get "userpage_edit", to: "userpage#edit_user"
    get "mycards", to: "posts#mycards"
  end
  get 'home/index'
  root "home#index"
  

  devise_for :users, skip: [:passwords, :confirmations, :unlocks, :sessions, :registrations],  controllers: {
        omniauth_callbacks: "users/omniauth_callbacks"
      }


  devise_scope :user do
    patch "update", to: "users/edit_user#update"
    get "sign_in_modal", to: "users/log_in#login"
    post "sign_up_modal", to: "users/sign_up#signup"
    get "sign_in", to: "users/sessions#new", as: :new_user_session
    post "sign_in", to: "users/sessions#create", as: :user_session
    delete "sign_out", to: "users/sessions#destroy", as: :destroy_user_session
    get "sign_up", to: "users/registrations#new", as: :new_user_registration
    post "sign_up", to: "users/registrations#create", as: :user_registration
  end

  

  concern :chattable do
    resources :chats, only: [:show] do
      resources :messages, only: [:create]
    end
  end

  resources :posts, concerns: :chattable
  resources :chats, only: [:index]

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/post.rb
class Post < ApplicationRecord
    has_many_attached :photos
    belongs_to :user
    has_one :location, dependent: :destroy
    has_many :chat, dependent: :destroy
    has_many :message, dependent: :destroy
    accepts_nested_attributes_for :location
    validate :validate_photos_count
    

      scope :price_less_than, ->(price) { where("price <= ?", price) }
      scope :in_city, ->(city) { where(city: city) }
      scope :with_meters, ->(square_meters) { where("square_meters <= ?", square_meters) }
      scope :near_location, ->(address, radius) { 
        loc = Location.new(address: address)
        result = loc.geocode
        if result.nil?
          none
        else
          locations =Location.near(result, radius) 
          joins(:location).where(locations: { id: locations.map(&:id) })
        end
      }

      

      private
    
      def validate_photos_count
        if photos.size > 10
          errors.add(:photos, "You can upload a maximum of 10 photos.")
        end
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @user = @post.user
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.build_location
  end

  # GET /posts/1/edit
  def edit
  end

  def mycards
    @posts = current_user.posts
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      new_params = post_params.dup
      if new_params[:photos].blank?
        new_params.delete(:photos)
      end
      if @post.update(new_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :price, :numer_rooms, :square_meters, :city, :floor, photos: [], location_attributes: [:address])
      
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display_photos.html.erb
<% if @post.photos.attached? %>
  <div id="postPhotosCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @post.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= 'active' if index.zero? %>">
          <%= image_tag photo, class: 'd-block w-100 img-fluid',style: "height: 1000px; object-fit: contain;", alt: "Photo #{index + 1}" %>
        </div>
      <% end %>
    </div>
    <% if @post.photos.count > 1 %>
      <button class="carousel-control-prev" type="button" data-bs-target="#postPhotosCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#postPhotosCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    <% end %>
  </div>

  <div class="row mt-3">
    <% @post.photos.each_with_index do |photo, index| %>
      <div class="col">
        <a href="#" data-bs-target="#postPhotosCarousel" data-bs-slide-to="<%= index %>" class="d-block">
          <%= image_tag photo, class: 'img-thumbnail',style: "height: 200px; object-fit: contain;", alt: "Thumbnail #{index + 1}" %>
        </a>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-muted">No photos available for this post.</p>
<% end %>

<style>
    .carousel-control-prev,
    .carousel-control-next {
      width: 5%;
      opacity: 0.8;
    }
    .carousel-control-prev-icon,
    .carousel-control-next-icon {
      background-color: rgba(0, 0, 0, 0.5);
      background-size: 50% 50%;
      border-radius: 50%;
      width: 44px;
      height: 44px;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .carousel-control-prev-icon::after,
    .carousel-control-next-icon::after {
      content: '';
      display: block;
      width: 20px;
      height: 20px;
      border-top: 3px solid white;
      border-left: 3px solid white;
    }
    .carousel-control-prev-icon::after {
      transform: rotate(-45deg);
      margin-left: 5px;
    }
    .carousel-control-next-icon::after {
      transform: rotate(135deg);
      margin-right: 5px;
    }
    .carousel-control-prev:hover .carousel-control-prev-icon,
    .carousel-control-next:hover .carousel-control-next-icon {
      background-color: rgba(0, 0, 0, 0.7);
    }
  </style>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title text-center">Edit your House Card</h3>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <%= form_with(model: @post, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :title, style: "display: block" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :photos, style: "display: block" %>
              <%= form.file_field :photos, multiple: true, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, style: "display: block" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.fields_for :location do |location_form| %>
                <%= location_form.label :address, style: "display: block" %>
                <%= location_form.text_field :address, class: "form-control" %>
              <% end %>
            </div>

            <div class="mb-3">
              <%= form.label :city %>
              <%= form.select :city, options_for_select(['Rome', 'Milan', 'Pisa'], @post.city), class: "form-select" %>
            </div>
            <div class="mb-3">
              <%= form.label :price, style: "display: block" %>
              <%= form.number_field :price, step: '1', min: '0', class: "form-control", placeholder: "$ or euro" %>
            </div>

            <div class="mb-3">
              <%= form.label :numer_rooms, style: "display: block" %>
              <%= form.number_field :numer_rooms, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :square_meters, style: "display: block" %>
              <%= form.number_field :square_meters, step: :any, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :floor, style: "display: block" %>
              <%= form.number_field :floor, class: "form-control" %>
            </div>
            
            <div class="text-center">
              <%= form.submit 'Update', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/mycards.html.erb
<div class="container mt-5">
  <h1 class="text-center">My Houses</h1>
  <% @posts.each do |post| %>
    <div class="card mb-3">
      <div class="card-body text-center">
        <h3 class="card-title"><%= post.title %></h3>

        <% if post.photos.attached? %>
          <div class="row justify-content-center mb-3">
            <%= image_tag post.photos[0], class: "img-fluid", style: "width: 400px; height: 400px;" %>
          </div>
        <%else%>
           <div class="row justify-content-center mb-3">
            <%= image_tag "logo.png", class: 'img-fluid' , style: "width: 400px; height: 400px;" %>
          </div>
        <% end %>

        <p class="card-text"><strong>Description:</strong> <%= post.description %></p>
        <p class="card-text"><strong>address:</strong> <%= post.location.address %></p>
        <p class="card-text"><strong>city:</strong> <%= post.city %></p>
        <p class="card-text"><strong>Price:</strong> <%= number_to_currency(post.price) %></p>
        <p class="card-text"><strong>Number of Rooms:</strong> <%= post.numer_rooms %></p>
        <p class="card-text"><strong>Square Meters:</strong> <%= post.square_meters %></p>
        <p class="card-text"><strong>Floor:</strong> <%= post.floor %></p>

        <div class="text-center mt-3">
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to 'Show', post_path(post), class: "btn btn-secondary" %>
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %>
            <%= button_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </div>


      </div>
    </div>
  <% end %>
  <div class="text-center mt-5">
    <%= link_to 'Post a New House', new_post_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title text-center">Make your House Card</h3>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <%= form_with(model: @post) do |form| %>
            <div class="mb-3">
              <%= form.label :title, style: "display: block" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :photos, style: "display: block" %>
              <%= form.file_field :photos, multiple: true, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, style: "display: block" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.fields_for :location do |location_form| %>
                <%= location_form.label :address, style: "display: block" %>
                <%= location_form.text_field :address, class: "form-control" %>
              <% end %>
            </div>

          
            <div class="mb-3">
              <%= form.label :city %>
              <%= form.select :city, options_for_select(['Rome', 'Milan', 'Pisa']),class: "form-select" %>
            </div>
            <div class="mb-3">
              <%= form.label :price, style: "display: block" %>
              <%= form.number_field :price, step: '1', min: '0', class: "form-control", placeholder: "$ or euro" %>
            </div>

            <div class="mb-3">
              <%= form.label :numer_rooms, style: "display: block" %>
              <%= form.number_field :numer_rooms, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :square_meters, style: "display: block" %>
              <%= form.number_field :square_meters, step: :any, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :floor, style: "display: block" %>
              <%= form.number_field :floor, class: "form-control" %>
            </div>
            
            <div class="text-center">
              <%= form.submit 'Create', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <h2 class="card-title text-center mb-4"><%= @post.title %></h2>
      <% if @post.photos.attached? %>
        <%= render "posts/display_photos" %>
      <% else %>
        <div class="text-center">
          <%= image_tag "logo.png", class: 'img-fluid', style: "max-width: 400px; max-height: 400px; width: auto; height: auto;" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <h3 class="card-title text-center mb-4">Property Details</h3>
      <div class="row">
        <div class="information col-md-6">
          <p><strong>Address:</strong> <%= @post.location.address %></p>
          <p><strong>City:</strong> <%= @post.city %></p>
          <p><strong>Number of Rooms:</strong> <%= @post.numer_rooms %></p>
          <p><strong>Price:</strong> <%= number_to_currency(@post.price) %></p>
          <p><strong>Square Meters:</strong> <%= @post.square_meters %></p>
          <p><strong>Floor Number:</strong> <%= @post.floor %></p>
        </div>
        <div class="col-md-6">
          <% if @post.location.map_image.attached? %>
            <div class="text-center">
              <%= image_tag @post.location.map_image, class: "img-fluid", style: "max-width: 100%; height: auto;" %>
            </div>
          <% else %>
            <div class="text-center text-muted">Map image not available</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <h3 class="card-title text-center mb-4">Owner Profile</h3>
      <div class="row">
        <div class="col-md-4 text-center">
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar, class: 'rounded-circle mb-3', style: "width: 150px; height: 150px; object-fit: cover; border: 2px solid #007bff;" %>
          <% else %>
            <% if @user && @user.provider == "google_oauth2" %>
              <%= image_tag(@user.avatar_url, class: "rounded-circle mb-3",  style: "width: 150px; height: 150px; object-fit: cover; border: 2px solid #007bff;") %>
            <% else %>
              <%= image_tag "logo.png", class: 'rounded-circle mb-3', style: "width: 150px; height: 150px; object-fit: cover;" %>
            <%end%>
          <% end %>
          <p><strong><%= @user.full_name %></strong></p>
          <p class="text-muted"><%= @user.email %></p>
          <% if current_user && current_user == @user %>
            <%= link_to 'Modify Post', edit_post_path(@post), class: 'btn btn-warning mt-3' %>
          <% end %>
        </div>
        <div class="col-md-8">
          <% if current_user && current_user != @user %>
            <h5>Send a Message:</h5>
            <%= form_with url: post_chat_messages_path(@post, chat_id: 'new'), local: true do |form| %>
              <div class="mb-3">
                <%= form.text_area :content, name: 'message[content]', class: "form-control", rows: 4 %>
              </div>
              <div class="d-flex justify-content-center align-items-center gap-2">
                <%= form.submit 'Send Message', class: "btn btn-primary text-center" %>
                <% chat = Chat.find_by(post: @post, buyer: current_user, owner: @user) %>
                <% if chat&.messages&.any? %>
                  <%= link_to 'View Conversation', post_chat_path(@post, chat), class: 'btn btn-secondary text-center' %>
                <% end %>
              </div>
            <% end %>
          <% elsif current_user && current_user == @user %>
            <div class="text-center mt-4">
              <%= image_tag "star.png", class: 'rounded-circle mb-3', style: "width: 100px; height: 100px; object-fit: cover;" %>
              <h5>This is your post!</h5>
            </div>
          <% else %>
            <div class="text-center mt-4">
              <%= image_tag "message.png", class: 'rounded-circle mb-3', style: "width: 100px; height: 100px; object-fit: cover;" %>
              <h5>Log in to send a message</h5>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show_old.html.erb
<div class="container mt-5">
  <div class="custom-card card">
    <div class="card-body">
      <h3 class="card-title text-center"><%= @post.title%> </h3>
      <div class="row justify-content-center">
        <div class="col-md-4 text-center">
          <% if @post.photos.attached? %>
            <%= render "posts/display_photos"%>
          <% else %>
            <%= image_tag "logo.png", class: 'profile-avatar' , style: "width: 400px; height: 400px; border-radius: 50%; object-fit: cover;" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card bg-light border-0">
  <div class="card-body">
    <h3 class="card-title text-center mb-4">Property Details</h3>
    <div class="row">
      <div class="col-md-6">
        <p class="mb-3"><strong>City:</strong> <%= @post.location.address %></p>
        <p class="mb-3"><strong>City:</strong> <%= @post.city %></p>
        <p class="mb-3"><strong>Number of Rooms:</strong> <%= @post.numer_rooms %></p>
        <p class="mb-3"><strong>Price:</strong> <%= number_to_currency(@post.price) %></p>
        <p class="mb-3"><strong>Square Meters:</strong> <%= @post.square_meters %></p>
        <p class="mb-3"><strong>Floor Number:</strong> <%= @post.floor %></p>
      </div>
      <div class="col-md-6 text-center">
        <% if @post.location.map_image.attached? %>
          <%= image_tag @post.location.map_image, class: "img-fluid", style: "max-height: 400px;" %>
        <% else %>
          <p>Map image not available</p>
        <% end %>
      </div>
    </div>
  </div>
</div>


  <div class="card", style="border: none;">
  <div class="card-body">
    <h3 class="card-title text-center">User Profile</h3>
    <div class="row">
      <div class="col-md-4 text-center bg-light">
        <h5 class="">Profile picture:</h5>
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: 'profile-avatar', style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" %>
        <% else %>
          <%= image_tag "logo.png", class: 'profile-avatar', style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" %>
        <% end %>
        <div class="card-body bg-light">
          <p class="card-text"><strong>Owner Name:</strong> <%= @user.full_name %></p>
          <p class="card-text"><strong>Owner Email:</strong> <%= @user.email %></p>
        </div>
      </div>
      <div class="col-md-8">
        <% if current_user && current_user != @user %>
          <h5>Send a Message:</h5>
            <%= form_with url: post_chat_messages_path(@post, chat_id: 'new'), local: true do |form| %>
              <div class="mb-3">
                <%= form.text_area :content, name: 'message[content]', class: "form-control", style: "width: 100%; height: 100%; min-height: 200px;" %>
              </div>
              <div class="d-flex justify-content-center align-items-center gap-2">
                <%= form.submit 'Send Message', class: "btn btn-primary" %>
                <% chat = Chat.find_by(post: @post, user1: current_user, user2: @user) %>
                <% if chat&.messages&.any? %>
                  <%= link_to 'View Conversation', post_chat_path(@post, chat), class: 'btn btn-secondary' %>
                <% end %>
              </div>
            <% end %>
        <% elsif current_user && current_user == @user %>
          <div class="col mt-5 text-center">
            <%= image_tag "star.png", class: 'profile-avatar text-center', style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" %>
            <h5>This is your post!</h5>
          </div>
        <% else %>
          <div class="col mt-5 text-center">
            <%= image_tag "message.png", class: 'profile-avatar text-center', style: "width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" %>
            <h5>Log in to send a message</h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>