config/routes.rb
Rails.application.routes.draw do

  authenticated :user, ->(user) { user.admin?} do
    namespace :admin do
      get 'dashboard', to: 'dashboard#index'
    end
  end
  
  authenticated :user do
    get 'notifications/:id', to: 'notifications#mark_and_redirect', as: 'mark_and_redirect_notification'
    get 'userpage', to: "userpage#show"
    get "userpage_edit", to: "userpage#edit_user"
    get "mycards", to: "posts#mycards"
  end
  get 'home/index'
  root "home#index"
  

  devise_for :users, skip: [:passwords, :confirmations, :unlocks, :sessions, :registrations],  controllers: {
        omniauth_callbacks: "users/omniauth_callbacks"
      }


  devise_scope :user do
    patch "update", to: "users/edit_user#update"
    get "sign_in_modal", to: "users/log_in#login"
    post "sign_up_modal", to: "users/sign_up#signup"
    get "sign_in", to: "users/sessions#new", as: :new_user_session
    post "sign_in", to: "users/sessions#create", as: :user_session
    delete "sign_out", to: "users/sessions#destroy", as: :destroy_user_session
    get "sign_up", to: "users/registrations#new", as: :new_user_registration
    post "sign_up", to: "users/registrations#create", as: :user_registration
  end

  

  concern :chattable do
    resources :chats, only: [:show] do
      resources :messages, only: [:create]
    end
  end

  resources :posts, concerns: :chattable
  resources :chats, only: [:index]

  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/modals/_sign_in_modal.html.erb
<div class="modal" tabindex="-1" id="UserModal" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Log in</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: sign_in_modal_path, method: :get , scope: :user do |f|%>
            <div class="mb-3">
              <%= f.label "Email:", class: "form-label" %>
                <%= f.email_field :email, class: "form-control", placeholder: "john@email.com", minlength: 5, maxlength: 20 %>  
            </div>
            <div class="mb-3">
              <%= f.label :password %><br>
              <%= f.password_field :password, autocomplete: "current-password", class: "form-control", minlength: 5, maxlength: 20 %>
            </div>
            <div class="d-grid gap-2">
                <%= f.submit "Continue", class:"btn btn-danger" %>
            </div>
        <%end%>

        <hr class="hr hr-blurry" />
        <div class="d-grid gap-2 text-center">
            

            <%= button_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-outline-primary', data: { turbo: false } do %>
              Log in with Google <%= image_tag 'googlemini_logo.svg', class: 'bi', size: '20x20' %>
            <% end %>

        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/modals/_sign_up_modal.html.erb
<div class="modal" tabindex="-1" id="SignUpModal" aria-labelledby="exampleModalLabel" aria-hidden="true"  >
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Sign up </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"  data-controller="form-validation">
                <%= form_with url: sign_up_modal_path, method: :post , scope: :user   do |f|%>
                  <div class="field">
                    <%= f.label "full name" %><br />
                    <%= f.text_field :full_name, autofocus: true, autocomplete: "your full name ", class:"form-control" , placeholder: "John Smith ",  minlength: 5, maxlength: 50 ,data: { target: "form-validation.name" } ,required: true %>
                    <div data-target="form-validation.nameError" class="text-danger"></div>
                  </div>
                  <div class="mb-3">
                      <%=f.label "Email:", class:"form-label"%>
                      <%=f.email_field :email, class:"form-control" , placeholder: "john@email.com", data: { target: "form-validation.email" } ,required: true%>  
                      <div data-target="form-validation.emailError" class="text-danger"></div>
                  </div>
                  <div class="mb-3">
                      <%= f.label :password %><br>
                      <%= f.password_field :password, autocomplete: "new-password" , class:"form-control" , minlength: 5, maxlength: 50  , data: { target: "form-validation.password" },required: true%>
                      <div data-target="form-validation.passwordError" class="text-danger"></div>
                  </div>
                  <div class="mb-3">
                      <%= f.label :password_confirmation %><br />
                      <%= f.password_field :password_confirmation, autocomplete: "new-password" , class:"form-control", data: { target: "form-validation.passwordConfirmation" } , required: true%>
                      <div data-target="form-validation.passwordConfirmationError" class="text-danger"></div>
                  </div>
                  <div class="d-grid gap-2">
                      <%= f.submit "Sign Up", class:"btn btn-danger" , data: { target: "form-validation.submitButton" }%>
                  </div>
                <%end%>
        <hr class="hr hr-blurry" />
        <div class="d-grid gap-2 text-center">
            

            <%= button_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-outline-primary',data: { turbo: false } do %>
              Sign Up with Google <%= image_tag 'googlemini_logo.svg', class: 'bi', size: '20x20' %>
            <% end %>

        </div> 
    </div>
  </div>
</div>

app/views/modals/_user_modal.html.erb
<div class="modal" tabindex="-1" id="UserModal" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Log in</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: sign_in_path, method: :get  do |f|%>
            <div class="mb-3">
                <%=f.label "Email:", class:"form-label"%>
                <%=f.email_field :email, class:"form-control" , placeholder: "john@email.com"%>  
            </div>
            <div class="mb-3">
                <%= f.label :password %><br>
                <%= f.password_field :password, autocomplete: "current-password" , class:"form-control" %>
            </div>
            <div class="d-grid gap-2">
                <%= f.submit "Continue", class:"btn btn-danger" %>
            </div>
        <%end%>

        <hr class="hr hr-blurry" />
        <div class="d-grid gap-2 text-center">
            

            <%= button_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-outline-primary', data: { turbo: false } do %>
              Log in with Google <%= image_tag 'googlemini_logo.svg', class: 'bi', size: '20x20' %>
            <% end %>

        </div>
      </div>
    </div>
    
  </div>
</div>